version: "3.4"
services:
  
  backend:
    image: 'backend'
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - SERVER_NAME='localhost'
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    image: 'frontend'
    ports:
      - 80:80
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_ENV: 'production'

